services:
  - type: web
    name: azt-api
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && npm prune --production
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: APP_NAME
        value: AZT API
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DATABASE_URL
        sync: false
